
language: objective-c
osx_image: xcode8.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=SwiftyZeroMQ.xcodeproj

    # iOS
    - IOS_SDK=iphonesimulator10.1
    - IOS_FRAMEWORK_SCHEME="SwiftyZeroMQ-iOS"

    # macOS
    - MACOS_SDK=macosx10.12
    - MACOS_FRAMEWORK_SCHEME="SwiftyZeroMQ-macOS"

    # tvOS
    - TVOS_SDK=appletvsimulator10.0
    - TVOS_FRAMEWORK_SCHEME="SwiftyZeroMQ-tvOS"

    # watchOS
    - WATCHOS_SDK=watchsimulator3.1
    - WATCHOS_FRAMEWORK_SCHEME="SwiftyZeroMQ-watchOS"

  matrix:
    # iOS 10.0
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"
      SIMULATOR_NAME="iPhone 7 Plus (10.0)"
      SCHEME="$IOS_FRAMEWORK_SCHEME"
      SDK="$IOS_SDK"
      RUN_TESTS="YES"
      POD_LINT="YES"
      EXAMPLE_PROJECT="Example-iOS"

    # iOS 9.0
    - DESTINATION="OS=9.0,name=iPhone 5"
      SIMULATOR_NAME="iPhone 5 (9.0)"
      SCHEME="$IOS_FRAMEWORK_SCHEME"
      SDK="$IOS_SDK"
      RUN_TESTS="YES"
      POD_LINT="NO"
      EXAMPLE_PROJECT="Example-iOS"

    # macOS, no need for a simulator :)
    - DESTINATION="arch=x86_64"
      SIMULATOR_NAME=""
      SCHEME="$MACOS_FRAMEWORK_SCHEME"
      SDK="$MACOS_SDK"
      RUN_TESTS="YES"
      POD_LINT="NO"
      EXAMPLE_PROJECT="Example-macOS"

    # tvOS 10.0
    - DESTINATION="OS=10.0,name=Apple TV 1080p"
      SIMULATOR_NAME="Apple TV 1080p (10.0)"
      SCHEME="$TVOS_FRAMEWORK_SCHEME"
      SDK="$TVOS_SDK"
      RUN_TESTS="YES"
      POD_LINT="NO"
      EXAMPLE_PROJECT="Example-tvOS"

    # tvOS 9.0
    - DESTINATION="OS=9.0,name=Apple TV 1080p"
      SIMULATOR_NAME="Apple TV 1080p (9.0)"
      SCHEME="$TVOS_FRAMEWORK_SCHEME"
      SDK="$TVOS_SDK"
      RUN_TESTS="YES"
      POD_LINT="NO"
      EXAMPLE_PROJECT="Example-tvOS"

    # watchOS 3.1 (no tests, just build)
    - DESTINATION="OS=3.1,name=Apple Watch - 42mm"
      SIMULATOR_NAME=""
      SCHEME="$WATCHOS_FRAMEWORK_SCHEME"
      SDK="$WATCHOS_SDK"
      RUN_TESTS="NO"
      POD_LINT="NO"
      EXAMPLE_PROJECT="Example-watchOS"

    # watchOS 2.0 (no tests, just build)
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm"
      SIMULATOR_NAME=""
      SCHEME="$WATCHOS_FRAMEWORK_SCHEME"
      SDK="$WATCHOS_SDK"
      RUN_TESTS="NO"
      POD_LINT="NO"
      EXAMPLE_PROJECT="Example-watchOS"

before_install:
  # Install CocoaPods
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

script:
  # Set pipe fail flag
  - set -o pipefail

  # show debug information
  - xcodebuild -version
  - xcodebuild -showsdks

  # Prelaunch simulator and wait a bit
  # Use simulator id, please see https://github.com/travis-ci/travis-ci/issues/4906
  - if [ "$SIMULATOR_NAME" != "" ]; then
      echo Finding simulator id for \'$SIMULATOR_NAME\';
      SIMULATOR_ID=$(xcrun instruments -s | grep -o "$SIMULATOR_NAME \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/");
      echo Opening simulator with id \'$SIMULATOR_ID\';
      open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID;
      sleep 10;
    fi

  # Build framework in debug and run tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Workaround to random travis CI failure
  # See https://github.com/travis-ci/travis-ci/issues/4725
  - sleep 10

  # Build framework in release and run tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Example project in Debug
  - if [ $EXAMPLE_PROJECT == "Example-watchOS" ]; then
      (cd "$EXAMPLE_PROJECT" && (xcodebuild -project "Example-watchOS.xcodeproj" -scheme "Example-watchOS WatchKit App"  -destination "OS=10.0,name=iPhone 7 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty));
    else
      (cd "$EXAMPLE_PROJECT" && (xcodebuild -project "${EXAMPLE_PROJECT}.xcodeproj" -scheme "$EXAMPLE_PROJECT" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty));
    fi

  # Run CocoaPods pod validation if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi

  # Workaround to random travis CI failure
  # See https://github.com/travis-ci/travis-ci/issues/4725
  - sleep 10
